const channelsActionTypes = {
  OPEN_ADD_CHANNEL_FORM: "OPEN_ADD_CHANNEL_FORM",
  CLOSE_ADD_CHANNEL_FORM: "CLOSE_ADD_CHANNEL_FORM",

  SET_CURRENT_CHANNEL: "SET_CURRENT_CHANNEL",

  ADD_CHANNEL_START: "ADD_CHANNEL_START",
  ADD_CHANNEL_SUCCESS: "ADD_CHANNEL_SUCCESS",
  ADD_CHANNEL_FAILURE: "ADD_CHANNEL_FAILURE",

  GET_ALL_CHANNELS: "GET_ALL_CHANNELS"
};

export default channelsActionTypes;
